trigger:
  - main

parameters:
  - name: environment
    type: string
    default: dev
    values:
      - dev
      - uat
      - prod
  - name: resourceGroupName
    type: string
    default: rg-ae-test
  - name: azureServiceConnection
    type: string
    default: AzureServiceConnection

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Deploy
    displayName: Deploy Infrastructure
    jobs:
      - job: DeployBicep
        steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: Deploy Bicep
            inputs:
              azureSubscription: ${{ parameters.azureServiceConnection }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment group create \
                  --resource-group "${{ parameters.resourceGroupName }}" \
                  --template-file bicep/main.bicep \
                  --parameters @variables/parameters.${{ parameters.environment }}.json \
                  --parameters environment=${{ parameters.environment }}